/**
 * Deterministic exports for the executive insight artifact. The inline card is
 * the primary surface; these are the "send it onward" side door (Markdown for
 * pasting, a standalone print-friendly HTML page). All values come from the
 * already-computed InsightRecord — no recomputation, no model calls.
 */

import { formatKpiValue, VERDICT_LABEL, type InsightRecord } from "@/lib/insight/client";

export function insightSlug(insight: InsightRecord): string {
  return (
    insight.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "executive-briefing"
  );
}

function formatDay(iso: string): string {
  const date = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(date.getTime())) return iso;
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });
}

export function buildInsightMarkdown(insight: InsightRecord): string {
  const kpiRows = insight.kpis
    .map((kpi) => {
      const delta = kpi.deltaPct === undefined ? "—" : `${kpi.deltaPct > 0 ? "+" : ""}${kpi.deltaPct}%`;
      return `| ${kpi.label} | ${formatKpiValue(kpi.value, kpi.unit)} | ${delta} |`;
    })
    .join("\n");

  const actuals = insight.series.filter((p) => !p.projected).slice(-10);
  const seriesRows = actuals
    .map((p) => `| ${formatDay(p.date)} | $${p.sales.toLocaleString()} | $${p.overhead.toLocaleString()} | $${p.net.toLocaleString()} | $${p.balance.toLocaleString()} |`)
    .join("\n");

  const drivers = insight.verdict.drivers.map((d) => `- ${d}`).join("\n");

  return `# ${insight.title}

> ${VERDICT_LABEL[insight.verdict.status]} — ${insight.verdict.headline}

**Question:** ${insight.question}
**Source:** ${insight.datasetName} · as of ${formatDay(insight.asOf)}

## Key metrics
| Metric | Value | Δ vs prior |
| --- | --- | --- |
${kpiRows}

## What's driving this
${drivers || "_No drivers recorded._"}
${insight.verdict.detail ? `\n${insight.verdict.detail}\n` : ""}
## Recent daily detail
| Day | Sales | Overhead | Net | Balance |
| --- | --- | --- | --- | --- |
${seriesRows}

_Generated by Nexus from ${insight.source === "dataset" ? "your project data" : "the finance sample model"}._
`;
}

function esc(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Build a self-contained SVG line of the cash balance (actual + projected). */
function balanceSvg(insight: InsightRecord): string {
  const points = insight.series.slice(-44);
  if (points.length < 2) return "";
  const w = 760;
  const h = 220;
  const pad = 24;
  const values = points.map((p) => p.balance);
  const min = Math.min(0, ...values);
  const max = Math.max(...values);
  const span = max - min || 1;
  const x = (i: number) => pad + (i / (points.length - 1)) * (w - pad * 2);
  const y = (v: number) => h - pad - ((v - min) / span) * (h - pad * 2);
  const firstProjected = points.findIndex((p) => p.projected);
  const zeroY = y(0);

  const actualPath = points
    .map((p, i) => (p.projected ? null : `${i === 0 ? "M" : "L"}${x(i).toFixed(1)},${y(p.balance).toFixed(1)}`))
    .filter(Boolean)
    .join(" ");
  const projStart = firstProjected > 0 ? firstProjected - 1 : 0;
  const projPath = points
    .slice(projStart)
    .map((p, idx) => `${idx === 0 ? "M" : "L"}${x(projStart + idx).toFixed(1)},${y(p.balance).toFixed(1)}`)
    .join(" ");
  const accent = insight.verdict.status === "at_risk" ? "#ff6b57" : insight.verdict.status === "watch" ? "#d5a132" : "#03dc5d";

  return `<svg viewBox="0 0 ${w} ${h}" width="100%" role="img" aria-label="Cash balance trajectory">
    <line x1="${pad}" y1="${zeroY.toFixed(1)}" x2="${w - pad}" y2="${zeroY.toFixed(1)}" stroke="#ff6b57" stroke-dasharray="4 4" stroke-opacity="0.6" />
    <path d="${actualPath}" fill="none" stroke="${accent}" stroke-width="2.5" />
    ${firstProjected !== -1 ? `<path d="${projPath}" fill="none" stroke="${accent}" stroke-width="2.5" stroke-dasharray="6 5" stroke-opacity="0.8" />` : ""}
  </svg>`;
}

export function buildInsightHtml(insight: InsightRecord): string {
  const accent = insight.verdict.status === "at_risk" ? "#ff6b57" : insight.verdict.status === "watch" ? "#d5a132" : "#03dc5d";
  const kpiCards = insight.kpis
    .map(
      (kpi) => `<div class="kpi">
        <div class="kpi-label">${esc(kpi.label)}</div>
        <div class="kpi-value">${esc(formatKpiValue(kpi.value, kpi.unit))}</div>
        <div class="kpi-delta">${kpi.deltaPct === undefined ? esc(kpi.hint ?? "") : `${kpi.deltaPct > 0 ? "+" : ""}${kpi.deltaPct}%`}</div>
      </div>`,
    )
    .join("");
  const drivers = insight.verdict.drivers.map((d) => `<li>${esc(d)}</li>`).join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(insight.title)}</title>
<style>
  :root { color-scheme: dark; --ink:#f7fbff; --muted:#9aa3ad; --line:rgba(233,240,245,.14); --accent:${accent}; --panel:#0c1014; }
  * { box-sizing:border-box; }
  body { margin:0; background:linear-gradient(180deg,#08080a,#050506 60%,#020304); color:var(--ink); font-family:"Mona Sans",Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif; padding:40px; }
  .wrap { max-width:840px; margin:0 auto; }
  .eyebrow { color:var(--accent); font-size:13px; font-weight:750; letter-spacing:.08em; text-transform:uppercase; }
  h1 { margin:6px 0 2px; font-size:30px; }
  .sub { color:var(--muted); font-size:14px; margin-bottom:20px; }
  .verdict { border:1px solid var(--line); border-left:3px solid var(--accent); border-radius:12px; background:rgba(255,255,255,.03); padding:18px 20px; margin-bottom:22px; }
  .verdict h2 { margin:0 0 6px; font-size:18px; }
  .verdict ul { margin:10px 0 0; padding-left:18px; color:var(--muted); font-size:14px; line-height:1.6; }
  .kpis { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin-bottom:24px; }
  .kpi { border:1px solid var(--line); border-radius:12px; background:rgba(255,255,255,.03); padding:14px 16px; }
  .kpi-label { color:var(--muted); font-size:12px; }
  .kpi-value { font-size:24px; font-weight:650; margin-top:4px; }
  .kpi-delta { color:var(--muted); font-size:12px; margin-top:2px; }
  .chart { border:1px solid var(--line); border-radius:12px; background:rgba(255,255,255,.02); padding:16px; margin-bottom:24px; }
  .chart h3 { margin:0 0 10px; font-size:13px; color:var(--muted); text-transform:uppercase; letter-spacing:.06em; }
  table { width:100%; border-collapse:collapse; font-size:13px; }
  th, td { text-align:right; padding:8px 10px; border-bottom:1px solid var(--line); }
  th:first-child, td:first-child { text-align:left; }
  th { color:var(--muted); font-size:11px; text-transform:uppercase; letter-spacing:.05em; }
  .foot { color:var(--muted); font-size:12px; margin-top:24px; }
  @media print { body { background:#fff; color:#111; } .kpi,.verdict,.chart { background:#fff; } }
  @media (max-width:640px) { .kpis { grid-template-columns:repeat(2,1fr); } }
</style>
</head>
<body>
  <div class="wrap">
    <div class="eyebrow">Executive briefing · ${esc(VERDICT_LABEL[insight.verdict.status])}</div>
    <h1>${esc(insight.title)}</h1>
    <div class="sub">${esc(insight.datasetName)} · as of ${esc(formatDay(insight.asOf))}</div>

    <div class="verdict">
      <h2>${esc(insight.verdict.headline)}</h2>
      ${insight.verdict.detail ? `<p class="sub" style="margin:0">${esc(insight.verdict.detail)}</p>` : ""}
      <ul>${drivers}</ul>
    </div>

    <div class="kpis">${kpiCards}</div>

    <div class="chart">
      <h3>Cash trajectory (dashed = projected)</h3>
      ${balanceSvg(insight)}
    </div>

    <div class="chart">
      <h3>Recent daily detail</h3>
      <table>
        <thead><tr><th>Day</th><th>Sales</th><th>Overhead</th><th>Net</th><th>Balance</th></tr></thead>
        <tbody>
          ${insight.series
            .filter((p) => !p.projected)
            .slice(-12)
            .map(
              (p) =>
                `<tr><td>${esc(formatDay(p.date))}</td><td>$${p.sales.toLocaleString()}</td><td>$${p.overhead.toLocaleString()}</td><td>$${p.net.toLocaleString()}</td><td>$${p.balance.toLocaleString()}</td></tr>`,
            )
            .join("")}
        </tbody>
      </table>
    </div>

    <div class="foot">Generated by Nexus from ${insight.source === "dataset" ? "your project data" : "the finance sample model"} · ${esc(insight.question)}</div>
  </div>
</body>
</html>`;
}
